---
title: "website_main"
format: html
editor: visual
---

### Using this notebook to work on the website traffic piece.

```{r}
library(tidyverse)
library(showtext)
library(elmer)
```

```{r}
font_add_google("Public Sans", "public_sans")
showtext_auto()
showtext_opts(dpi=300)
```

## Users by Device

```{r}
ga_fullsite_device <- ga_fullsite_device_raw |>
  rename(Date = `Month of Year`,
         Device = `Device Category`)
```

```{r}
ga_fullsite_device |>
  ggplot(aes(x = Date, 
             y = Users,
             color = Device))+
  geom_line(linewidth = 1)+
  geom_point(size = 2)+
  geom_text_repel(aes(label = Users),
                  point.padding = 5,
                  direction = "both",
                  nudge_y = 250000,
                  show.legend = FALSE)+
  scale_y_continuous(labels = scales::label_comma())+
  labs(x = NULL)+
  theme_minimal()+
  theme(
    text = element_text(family ="public_sans")
  )
```

```{r}
ga_fullsite_device |>
  pivot_wider(names_from = Date,
              values_from = Users)|>
  rename(apr_21 = `2021-04-01`,
         mar_21 = `2021-03-01`)|>
  mutate(perc_change = (apr_21 - mar_21) / (mar_21 + apr_21) * 100)

```

## Annotated finder search results

```{r}
web_search_annotated_raw |> 
  group_by(Category)|>
  summarize(March_21_count = sum(`March 2021 Search Queries`),
            April_21_count = sum(`April 2021 Search Queries`))|>
  arrange(desc(March_21_count))
```

```{r}
web_search_annotated_raw |> 
  group_by(Category)|>
  summarize(March_21_count = sum(`March 2021 Search Queries`),
            April_21_count = sum(`April 2021 Search Queries`),na.rm=TRUE)|>
  filter(!is.na(Category)) |>
  arrange(desc(March_21_count))|>
   pivot_longer(
    cols = c(March_21_count, April_21_count),  # Columns to pivot
    names_to = "Month",                       # New column for names
    values_to = "Value"                       # New column for values
  )|>
  ggplot(aes(x = reorder(Category,Value),
             y = Value,
             fill = Month
             
             ))+
  geom_col(linewidth = 1,
           position = "dodge")+
  scale_y_continuous(labels = scales::label_comma())+
  coord_flip()+
  labs(x = NULL)+
  theme_minimal()+
  theme(
    text = element_text(family ="public_sans")
  )
```

Vaccine related questions drop significantly. Turn these into slope charts.

```{r}
web_search_annotated_raw |> 
  group_by(Category)|>
  summarize(`2021-03-01` = sum(`March 2021 Search Queries`),
            `2021-04-01` = sum(`April 2021 Search Queries`),na.rm=TRUE)|>
  filter(!is.na(Category)) |>
  arrange(desc(`2021-03-01`))|>
   pivot_longer(
    cols = c(`2021-03-01`, `2021-04-01`),  
    names_to = "Month",                    
    values_to = "Value" 
  )|>
  mutate(Month = as.Date(Month))|>
  ggplot(aes(x = Month,
             y = Value,
             color = Category,
             group = Category)
         )+
  geom_line(linewidth = 1)+
  geom_point()+
  scale_y_continuous(labels = scales::label_comma())+
  labs(x = NULL)+
  theme_minimal()+
  theme(
    text = element_text(family ="public_sans")
  )
```

## Sentiment

```{r}
web_search_annotated_raw |>
  group_by(Sentiment) |>
  summarize(count = n(), .groups = "drop")
```

Sentiment data would be harder to glean. Majority of the searches are neutrally phrased.

## Usage data per visitor
